version: '3.8'

services:
  db-server:
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  rest-api:
    image: noerous/proyecto_grupo1_delivery:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db-server

volumes:
  postgresql-data:
